#FROM centos:centos8
FROM registry.access.redhat.com/ubi8/ubi

COPY buildroot.repo /etc/yum.repos.d/
COPY shim-unsigned-x64-15.5-1.el8.src.rpm /

RUN dnf -y install wget rpm-build
RUN dnf -y builddep --srpm /shim-unsigned-x64-*.src.rpm
RUN rm /etc/yum.repos.d/buildroot.repo
RUN rm /shim*.src.rpm
RUN dnf clean all
